services:
  - type: web
    name: dalor-sigop
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production


