// Sigop ERP - Módulo Financiero Orquestador Modular
// Submódulos importados e inicializados:
import './financial/cxc.js';
import './financial/cxp.js';
import './financial/fiscal_withholdings.js';
import './financial/treasury.js';
import './financial/quick_flow_partners.js';
import './financial/bank_accounts.js';

// Re-exportación unificada de compatibilidad ES6 para Rollup / Vite / Window
// --- cxc.js ---
export const openFinancialSubtab = (...args) => (typeof window !== 'undefined' && window.openFinancialSubtab ? window.openFinancialSubtab(...args) : undefined);
export const switchFinancialSubtab = (...args) => (typeof window !== 'undefined' && window.switchFinancialSubtab ? window.switchFinancialSubtab(...args) : undefined);
export const goToCxcPage = (...args) => (typeof window !== 'undefined' && window.goToCxcPage ? window.goToCxcPage(...args) : undefined);
export const changeCxcPageSize = (...args) => (typeof window !== 'undefined' && window.changeCxcPageSize ? window.changeCxcPageSize(...args) : undefined);
export const roundFinancial = (...args) => (typeof window !== 'undefined' && window.roundFinancial ? window.roundFinancial(...args) : undefined);
export const setFilterCxc = (...args) => (typeof window !== 'undefined' && window.setFilterCxc ? window.setFilterCxc(...args) : undefined);
export const filterCxcList = (...args) => (typeof window !== 'undefined' && window.filterCxcList ? window.filterCxcList(...args) : undefined);
export const renderReceivablesPaginated = (...args) => (typeof window !== 'undefined' && window.renderReceivablesPaginated ? window.renderReceivablesPaginated(...args) : undefined);
export const loadReceivablesList = (...args) => (typeof window !== 'undefined' && window.loadReceivablesList ? window.loadReceivablesList(...args) : undefined);
export const openNewReceivableModal = (...args) => (typeof window !== 'undefined' && window.openNewReceivableModal ? window.openNewReceivableModal(...args) : undefined);
export const onCxcClientChanged = (...args) => (typeof window !== 'undefined' && window.onCxcClientChanged ? window.onCxcClientChanged(...args) : undefined);
export const onCxcProjectChanged = (...args) => (typeof window !== 'undefined' && window.onCxcProjectChanged ? window.onCxcProjectChanged(...args) : undefined);
export const submitCreateReceivable = (...args) => (typeof window !== 'undefined' && window.submitCreateReceivable ? window.submitCreateReceivable(...args) : undefined);
export const openCxcHistoryModal = (...args) => (typeof window !== 'undefined' && window.openCxcHistoryModal ? window.openCxcHistoryModal(...args) : undefined);
export const toggleCxcGestionForm = (...args) => (typeof window !== 'undefined' && window.toggleCxcGestionForm ? window.toggleCxcGestionForm(...args) : undefined);
export const updateCxcHistorySummaryCards = (...args) => (typeof window !== 'undefined' && window.updateCxcHistorySummaryCards ? window.updateCxcHistorySummaryCards(...args) : undefined);
export const updateCxcScopeButtonsUI = (...args) => (typeof window !== 'undefined' && window.updateCxcScopeButtonsUI ? window.updateCxcScopeButtonsUI(...args) : undefined);
export const switchCxcHistoryScope = (...args) => (typeof window !== 'undefined' && window.switchCxcHistoryScope ? window.switchCxcHistoryScope(...args) : undefined);
export const loadCxcTimelineData = (...args) => (typeof window !== 'undefined' && window.loadCxcTimelineData ? window.loadCxcTimelineData(...args) : undefined);
export const renderCxcTimelineList = (...args) => (typeof window !== 'undefined' && window.renderCxcTimelineList ? window.renderCxcTimelineList(...args) : undefined);
export const viewCxcEvidence = (...args) => (typeof window !== 'undefined' && window.viewCxcEvidence ? window.viewCxcEvidence(...args) : undefined);
export const clearCxcEvidenceFile = (...args) => (typeof window !== 'undefined' && window.clearCxcEvidenceFile ? window.clearCxcEvidenceFile(...args) : undefined);
export const submitCxcFollowUpLog = (...args) => (typeof window !== 'undefined' && window.submitCxcFollowUpLog ? window.submitCxcFollowUpLog(...args) : undefined);
export const openReceiveClientPaymentModal = (...args) => (typeof window !== 'undefined' && window.openReceiveClientPaymentModal ? window.openReceiveClientPaymentModal(...args) : undefined);
export const onRcpClientChanged = (...args) => (typeof window !== 'undefined' && window.onRcpClientChanged ? window.onRcpClientChanged(...args) : undefined);
export const calcClientPaymentBs = (...args) => (typeof window !== 'undefined' && window.calcClientPaymentBs ? window.calcClientPaymentBs(...args) : undefined);
export const submitDirectClientPayment = (...args) => (typeof window !== 'undefined' && window.submitDirectClientPayment ? window.submitDirectClientPayment(...args) : undefined);
export const openCreateCxCForProject = (...args) => (typeof window !== 'undefined' && window.openCreateCxCForProject ? window.openCreateCxCForProject(...args) : undefined);
export const openBadDebtModal = (...args) => (typeof window !== 'undefined' && window.openBadDebtModal ? window.openBadDebtModal(...args) : undefined);
export const submitBadDebtWriteOff = (...args) => (typeof window !== 'undefined' && window.submitBadDebtWriteOff ? window.submitBadDebtWriteOff(...args) : undefined);
// --- cxp.js ---
export const loadPayablesList = (...args) => (typeof window !== 'undefined' && window.loadPayablesList ? window.loadPayablesList(...args) : undefined);
export const updateCxpFilterBadges = (...args) => (typeof window !== 'undefined' && window.updateCxpFilterBadges ? window.updateCxpFilterBadges(...args) : undefined);
export const onCxpSearchInput = (...args) => (typeof window !== 'undefined' && window.onCxpSearchInput ? window.onCxpSearchInput(...args) : undefined);
export const onCxpDocTypeFilterChange = (...args) => (typeof window !== 'undefined' && window.onCxpDocTypeFilterChange ? window.onCxpDocTypeFilterChange(...args) : undefined);
export const applyCxpDateFilter = (...args) => (typeof window !== 'undefined' && window.applyCxpDateFilter ? window.applyCxpDateFilter(...args) : undefined);
export const clearCxpDateFilter = (...args) => (typeof window !== 'undefined' && window.clearCxpDateFilter ? window.clearCxpDateFilter(...args) : undefined);
export const setFilterCxp = (...args) => (typeof window !== 'undefined' && window.setFilterCxp ? window.setFilterCxp(...args) : undefined);
export const goToCxpPage = (...args) => (typeof window !== 'undefined' && window.goToCxpPage ? window.goToCxpPage(...args) : undefined);
export const changeCxpPageSize = (...args) => (typeof window !== 'undefined' && window.changeCxpPageSize ? window.changeCxpPageSize(...args) : undefined);
export const renderPayablesPaginated = (...args) => (typeof window !== 'undefined' && window.renderPayablesPaginated ? window.renderPayablesPaginated(...args) : undefined);
export const onCxpModalDocTypeChange = (...args) => (typeof window !== 'undefined' && window.onCxpModalDocTypeChange ? window.onCxpModalDocTypeChange(...args) : undefined);
export const calcPayablePreview = (...args) => (typeof window !== 'undefined' && window.calcPayablePreview ? window.calcPayablePreview(...args) : undefined);
export const loadUnbilledWarehouseEntries = (...args) => (typeof window !== 'undefined' && window.loadUnbilledWarehouseEntries ? window.loadUnbilledWarehouseEntries(...args) : undefined);
export const loadExpenseConcepts = (...args) => (typeof window !== 'undefined' && window.loadExpenseConcepts ? window.loadExpenseConcepts(...args) : undefined);
export const openCreateConceptModal = (...args) => (typeof window !== 'undefined' && window.openCreateConceptModal ? window.openCreateConceptModal(...args) : undefined);
export const submitCreateExpenseConcept = (...args) => (typeof window !== 'undefined' && window.submitCreateExpenseConcept ? window.submitCreateExpenseConcept(...args) : undefined);
export const onCxpPayableTypeChanged = (...args) => (typeof window !== 'undefined' && window.onCxpPayableTypeChanged ? window.onCxpPayableTypeChanged(...args) : undefined);
export const onCxpWarehouseModeChange = (...args) => (typeof window !== 'undefined' && window.onCxpWarehouseModeChange ? window.onCxpWarehouseModeChange(...args) : undefined);
export const onCxpWarehouseEntrySelected = (...args) => (typeof window !== 'undefined' && window.onCxpWarehouseEntrySelected ? window.onCxpWarehouseEntrySelected(...args) : undefined);
export const addCxpMaterialRow = (...args) => (typeof window !== 'undefined' && window.addCxpMaterialRow ? window.addCxpMaterialRow(...args) : undefined);
export const onCxpMaterialRowMatChanged = (...args) => (typeof window !== 'undefined' && window.onCxpMaterialRowMatChanged ? window.onCxpMaterialRowMatChanged(...args) : undefined);
export const onMaterialCreatedFromCxp = (...args) => (typeof window !== 'undefined' && window.onMaterialCreatedFromCxp ? window.onMaterialCreatedFromCxp(...args) : undefined);
export const removeCxpMaterialRow = (...args) => (typeof window !== 'undefined' && window.removeCxpMaterialRow ? window.removeCxpMaterialRow(...args) : undefined);
export const calcCxpMaterialsTotal = (...args) => (typeof window !== 'undefined' && window.calcCxpMaterialsTotal ? window.calcCxpMaterialsTotal(...args) : undefined);
export const applyCxpMaterialsTotalToAmount = (...args) => (typeof window !== 'undefined' && window.applyCxpMaterialsTotalToAmount ? window.applyCxpMaterialsTotalToAmount(...args) : undefined);
export const openNewPayableModal = (...args) => (typeof window !== 'undefined' && window.openNewPayableModal ? window.openNewPayableModal(...args) : undefined);
export const submitCreatePayable = (...args) => (typeof window !== 'undefined' && window.submitCreatePayable ? window.submitCreatePayable(...args) : undefined);
export const openEditPayableModal = (...args) => (typeof window !== 'undefined' && window.openEditPayableModal ? window.openEditPayableModal(...args) : undefined);
export const calcEditPayableBsPreview = (...args) => (typeof window !== 'undefined' && window.calcEditPayableBsPreview ? window.calcEditPayableBsPreview(...args) : undefined);
export const calcEditPayableFromBs = (...args) => (typeof window !== 'undefined' && window.calcEditPayableFromBs ? window.calcEditPayableFromBs(...args) : undefined);
export const submitEditPayable = (...args) => (typeof window !== 'undefined' && window.submitEditPayable ? window.submitEditPayable(...args) : undefined);
export const deletePayablePrompt = (...args) => (typeof window !== 'undefined' && window.deletePayablePrompt ? window.deletePayablePrompt(...args) : undefined);
export const openPayableHistoryModal = (...args) => (typeof window !== 'undefined' && window.openPayableHistoryModal ? window.openPayableHistoryModal(...args) : undefined);
export const openDeclareBadDebtModal = (...args) => (typeof window !== 'undefined' && window.openDeclareBadDebtModal ? window.openDeclareBadDebtModal(...args) : undefined);
export const submitDeclareBadDebt = (...args) => (typeof window !== 'undefined' && window.submitDeclareBadDebt ? window.submitDeclareBadDebt(...args) : undefined);
// --- fiscal_withholdings.js ---
export const openWithholdingVoucherModal = (...args) => (typeof window !== 'undefined' && window.openWithholdingVoucherModal ? window.openWithholdingVoucherModal(...args) : undefined);
export const printWithholdingVoucher = (...args) => (typeof window !== 'undefined' && window.printWithholdingVoucher ? window.printWithholdingVoucher(...args) : undefined);
export const openIslrWithholdingVoucherModal = (...args) => (typeof window !== 'undefined' && window.openIslrWithholdingVoucherModal ? window.openIslrWithholdingVoucherModal(...args) : undefined);
export const printIslrWithholdingVoucher = (...args) => (typeof window !== 'undefined' && window.printIslrWithholdingVoucher ? window.printIslrWithholdingVoucher(...args) : undefined);
export const openMunicipalWithholdingVoucherModal = (...args) => (typeof window !== 'undefined' && window.openMunicipalWithholdingVoucherModal ? window.openMunicipalWithholdingVoucherModal(...args) : undefined);
export const printMunicipalWithholdingVoucher = (...args) => (typeof window !== 'undefined' && window.printMunicipalWithholdingVoucher ? window.printMunicipalWithholdingVoucher(...args) : undefined);
export const switchFiscalInnerTab = (...args) => (typeof window !== 'undefined' && window.switchFiscalInnerTab ? window.switchFiscalInnerTab(...args) : undefined);
export const loadFiscalBooksView = (...args) => (typeof window !== 'undefined' && window.loadFiscalBooksView ? window.loadFiscalBooksView(...args) : undefined);
export const downloadLibroVentasExcel = (...args) => (typeof window !== 'undefined' && window.downloadLibroVentasExcel ? window.downloadLibroVentasExcel(...args) : undefined);
export const downloadLibroComprasExcel = (...args) => (typeof window !== 'undefined' && window.downloadLibroComprasExcel ? window.downloadLibroComprasExcel(...args) : undefined);
export const printLibroVentasPDF = (...args) => (typeof window !== 'undefined' && window.printLibroVentasPDF ? window.printLibroVentasPDF(...args) : undefined);
export const printLibroComprasPDF = (...args) => (typeof window !== 'undefined' && window.printLibroComprasPDF ? window.printLibroComprasPDF(...args) : undefined);
export const openImportLibrosExcelModal = (...args) => (typeof window !== 'undefined' && window.openImportLibrosExcelModal ? window.openImportLibrosExcelModal(...args) : undefined);
export const submitImportLibrosExcel = (...args) => (typeof window !== 'undefined' && window.submitImportLibrosExcel ? window.submitImportLibrosExcel(...args) : undefined);
// --- treasury.js ---
export const calcFinTransBsEquiv = (...args) => (typeof window !== 'undefined' && window.calcFinTransBsEquiv ? window.calcFinTransBsEquiv(...args) : undefined);
export const onFinTransAccountChanged = (...args) => (typeof window !== 'undefined' && window.onFinTransAccountChanged ? window.onFinTransAccountChanged(...args) : undefined);
export const openClientRefundModal = (...args) => (typeof window !== 'undefined' && window.openClientRefundModal ? window.openClientRefundModal(...args) : undefined);
export const submitClientRefund = (...args) => (typeof window !== 'undefined' && window.submitClientRefund ? window.submitClientRefund(...args) : undefined);
export const openRecordPaymentModal = (...args) => (typeof window !== 'undefined' && window.openRecordPaymentModal ? window.openRecordPaymentModal(...args) : undefined);
export const submitFinancialPayment = (...args) => (typeof window !== 'undefined' && window.submitFinancialPayment ? window.submitFinancialPayment(...args) : undefined);
export const onTreasurySummaryPeriodChange = (...args) => (typeof window !== 'undefined' && window.onTreasurySummaryPeriodChange ? window.onTreasurySummaryPeriodChange(...args) : undefined);
export const resetTreasurySummaryFilters = (...args) => (typeof window !== 'undefined' && window.resetTreasurySummaryFilters ? window.resetTreasurySummaryFilters(...args) : undefined);
export const loadTreasurySummary = (...args) => (typeof window !== 'undefined' && window.loadTreasurySummary ? window.loadTreasurySummary(...args) : undefined);
export const getIsoDate = (...args) => (typeof window !== 'undefined' && window.getIsoDate ? window.getIsoDate(...args) : undefined);
export const formatDateDisplay = (...args) => (typeof window !== 'undefined' && window.formatDateDisplay ? window.formatDateDisplay(...args) : undefined);
export const applyTreasuryFilters = (...args) => (typeof window !== 'undefined' && window.applyTreasuryFilters ? window.applyTreasuryFilters(...args) : undefined);
export const handleTreasuryPeriodChange = (...args) => (typeof window !== 'undefined' && window.handleTreasuryPeriodChange ? window.handleTreasuryPeriodChange(...args) : undefined);
export const updateTreasuryTraceKpis = (...args) => (typeof window !== 'undefined' && window.updateTreasuryTraceKpis ? window.updateTreasuryTraceKpis(...args) : undefined);
export const resetTreasuryFilters = (...args) => (typeof window !== 'undefined' && window.resetTreasuryFilters ? window.resetTreasuryFilters(...args) : undefined);
export const printTreasuryTraceReport = (...args) => (typeof window !== 'undefined' && window.printTreasuryTraceReport ? window.printTreasuryTraceReport(...args) : undefined);
export const goToTreasuryPage = (...args) => (typeof window !== 'undefined' && window.goToTreasuryPage ? window.goToTreasuryPage(...args) : undefined);
export const changeTreasuryPageSize = (...args) => (typeof window !== 'undefined' && window.changeTreasuryPageSize ? window.changeTreasuryPageSize(...args) : undefined);
export const renderTreasuryTracePaginated = (...args) => (typeof window !== 'undefined' && window.renderTreasuryTracePaginated ? window.renderTreasuryTracePaginated(...args) : undefined);
export const setCashFlowRange = (...args) => (typeof window !== 'undefined' && window.setCashFlowRange ? window.setCashFlowRange(...args) : undefined);
export const onCashFlowMonthChange = (...args) => (typeof window !== 'undefined' && window.onCashFlowMonthChange ? window.onCashFlowMonthChange(...args) : undefined);
export const applyCashFlowDateFilter = (...args) => (typeof window !== 'undefined' && window.applyCashFlowDateFilter ? window.applyCashFlowDateFilter(...args) : undefined);
export const clearCashFlowDateFilter = (...args) => (typeof window !== 'undefined' && window.clearCashFlowDateFilter ? window.clearCashFlowDateFilter(...args) : undefined);
export const setCashFlowCurrency = (...args) => (typeof window !== 'undefined' && window.setCashFlowCurrency ? window.setCashFlowCurrency(...args) : undefined);
export const loadCashFlowMatrix = (...args) => (typeof window !== 'undefined' && window.loadCashFlowMatrix ? window.loadCashFlowMatrix(...args) : undefined);
export const renderCashFlowMatrixTable = (...args) => (typeof window !== 'undefined' && window.renderCashFlowMatrixTable ? window.renderCashFlowMatrixTable(...args) : undefined);
export const printCashFlowMatrixReport = (...args) => (typeof window !== 'undefined' && window.printCashFlowMatrixReport ? window.printCashFlowMatrixReport(...args) : undefined);
export const openTreasuryExchangeModal = (...args) => (typeof window !== 'undefined' && window.openTreasuryExchangeModal ? window.openTreasuryExchangeModal(...args) : undefined);
export const onTreasuryExchangeDateChanged = (...args) => (typeof window !== 'undefined' && window.onTreasuryExchangeDateChanged ? window.onTreasuryExchangeDateChanged(...args) : undefined);
export const openBcvRateHistoryModal = (...args) => (typeof window !== 'undefined' && window.openBcvRateHistoryModal ? window.openBcvRateHistoryModal(...args) : undefined);
export const selectBcvHistoricalRate = (...args) => (typeof window !== 'undefined' && window.selectBcvHistoricalRate ? window.selectBcvHistoricalRate(...args) : undefined);
export const onTreasuryExchangeTypeChanged = (...args) => (typeof window !== 'undefined' && window.onTreasuryExchangeTypeChanged ? window.onTreasuryExchangeTypeChanged(...args) : undefined);
export const calcTreasuryExchangeDiff = (...args) => (typeof window !== 'undefined' && window.calcTreasuryExchangeDiff ? window.calcTreasuryExchangeDiff(...args) : undefined);
export const submitTreasuryExchange = (...args) => (typeof window !== 'undefined' && window.submitTreasuryExchange ? window.submitTreasuryExchange(...args) : undefined);
// --- quick_flow_partners.js ---
export const openQuickFlowModal = (...args) => (typeof window !== 'undefined' && window.openQuickFlowModal ? window.openQuickFlowModal(...args) : undefined);
export const selectQuickType = (...args) => (typeof window !== 'undefined' && window.selectQuickType ? window.selectQuickType(...args) : undefined);
export const calcQuickBs = (...args) => (typeof window !== 'undefined' && window.calcQuickBs ? window.calcQuickBs(...args) : undefined);
export const calcQuickUsd = (...args) => (typeof window !== 'undefined' && window.calcQuickUsd ? window.calcQuickUsd(...args) : undefined);
export const submitQuickFlow = (...args) => (typeof window !== 'undefined' && window.submitQuickFlow ? window.submitQuickFlow(...args) : undefined);
export const loadPartnersWithdrawalsList = (...args) => (typeof window !== 'undefined' && window.loadPartnersWithdrawalsList ? window.loadPartnersWithdrawalsList(...args) : undefined);
export const populatePartnersFilterDropdown = (...args) => (typeof window !== 'undefined' && window.populatePartnersFilterDropdown ? window.populatePartnersFilterDropdown(...args) : undefined);
export const filterPartnersWithdrawals = (...args) => (typeof window !== 'undefined' && window.filterPartnersWithdrawals ? window.filterPartnersWithdrawals(...args) : undefined);
export const selectPartnerSummaryCard = (...args) => (typeof window !== 'undefined' && window.selectPartnerSummaryCard ? window.selectPartnerSummaryCard(...args) : undefined);
export const renderPartnersWithdrawalsPaginated = (...args) => (typeof window !== 'undefined' && window.renderPartnersWithdrawalsPaginated ? window.renderPartnersWithdrawalsPaginated(...args) : undefined);
export const goToPartnersPage = (...args) => (typeof window !== 'undefined' && window.goToPartnersPage ? window.goToPartnersPage(...args) : undefined);
export const changePartnersPageSize = (...args) => (typeof window !== 'undefined' && window.changePartnersPageSize ? window.changePartnersPageSize(...args) : undefined);
export const confirmDeletePartnerWithdrawal = (...args) => (typeof window !== 'undefined' && window.confirmDeletePartnerWithdrawal ? window.confirmDeletePartnerWithdrawal(...args) : undefined);
export const openNewPartnerWithdrawalModal = (...args) => (typeof window !== 'undefined' && window.openNewPartnerWithdrawalModal ? window.openNewPartnerWithdrawalModal(...args) : undefined);
// --- bank_accounts.js ---
export const openMaterialConsumeModalWithProject = (...args) => (typeof window !== 'undefined' && window.openMaterialConsumeModalWithProject ? window.openMaterialConsumeModalWithProject(...args) : undefined);
export const loadFinancialAccounts = (...args) => (typeof window !== 'undefined' && window.loadFinancialAccounts ? window.loadFinancialAccounts(...args) : undefined);
export const _fillAccountSelect = (...args) => (typeof window !== 'undefined' && window._fillAccountSelect ? window._fillAccountSelect(...args) : undefined);
export const openManageAccountsModal = (...args) => (typeof window !== 'undefined' && window.openManageAccountsModal ? window.openManageAccountsModal(...args) : undefined);
export const _renderAccountsList = (...args) => (typeof window !== 'undefined' && window._renderAccountsList ? window._renderAccountsList(...args) : undefined);
export const submitNewFinancialAccount = (...args) => (typeof window !== 'undefined' && window.submitNewFinancialAccount ? window.submitNewFinancialAccount(...args) : undefined);
export const deactivateFinancialAccount = (...args) => (typeof window !== 'undefined' && window.deactivateFinancialAccount ? window.deactivateFinancialAccount(...args) : undefined);
export const openInitialBalanceModal = (...args) => (typeof window !== 'undefined' && window.openInitialBalanceModal ? window.openInitialBalanceModal(...args) : undefined);
export const submitInitialBalance = (...args) => (typeof window !== 'undefined' && window.submitInitialBalance ? window.submitInitialBalance(...args) : undefined);
