// Sigop ERP - Módulo de Proyectos Orquestador Modular
// Submódulos importados e inicializados:
import './projects/projects_core.js';
import './projects/projects_tracking_wbs.js';
import './projects/projects_requisitions.js';
import './projects/projects_edit.js';

// Re-exportación unificada de compatibilidad ES6 para Rollup / Vite / Window
// --- projects_core.js ---
export const setProjectType = (...args) => (typeof window !== 'undefined' && window.setProjectType ? window.setProjectType(...args) : undefined);
export const onProjectLocationInput = (...args) => (typeof window !== 'undefined' && window.onProjectLocationInput ? window.onProjectLocationInput(...args) : undefined);
export const applyEditProjectSedeRules = (...args) => (typeof window !== 'undefined' && window.applyEditProjectSedeRules ? window.applyEditProjectSedeRules(...args) : undefined);
export const onEditProjectLocationInput = (...args) => (typeof window !== 'undefined' && window.onEditProjectLocationInput ? window.onEditProjectLocationInput(...args) : undefined);
export const switchProjectSubtab = (...args) => (typeof window !== 'undefined' && window.switchProjectSubtab ? window.switchProjectSubtab(...args) : undefined);
export const initProjectPlanningView = (...args) => (typeof window !== 'undefined' && window.initProjectPlanningView ? window.initProjectPlanningView(...args) : undefined);
export const populatePlanDropdownSelectors = (...args) => (typeof window !== 'undefined' && window.populatePlanDropdownSelectors ? window.populatePlanDropdownSelectors(...args) : undefined);
export const filterPlanSelect = (...args) => (typeof window !== 'undefined' && window.filterPlanSelect ? window.filterPlanSelect(...args) : undefined);
export const onPlanMaterialSelected = (...args) => (typeof window !== 'undefined' && window.onPlanMaterialSelected ? window.onPlanMaterialSelected(...args) : undefined);
export const updatePlanMaterialsCostTotal = (...args) => (typeof window !== 'undefined' && window.updatePlanMaterialsCostTotal ? window.updatePlanMaterialsCostTotal(...args) : undefined);
export const addPlanResource = (...args) => (typeof window !== 'undefined' && window.addPlanResource ? window.addPlanResource(...args) : undefined);
export const removePlanResource = (...args) => (typeof window !== 'undefined' && window.removePlanResource ? window.removePlanResource(...args) : undefined);
export const assignPersonnelTag = (...args) => (typeof window !== 'undefined' && window.assignPersonnelTag ? window.assignPersonnelTag(...args) : undefined);
export const removePersonnelTag = (...args) => (typeof window !== 'undefined' && window.removePersonnelTag ? window.removePersonnelTag(...args) : undefined);
export const assignVehicleTag = (...args) => (typeof window !== 'undefined' && window.assignVehicleTag ? window.assignVehicleTag(...args) : undefined);
export const removeVehicleTag = (...args) => (typeof window !== 'undefined' && window.removeVehicleTag ? window.removeVehicleTag(...args) : undefined);
export const assignToolTag = (...args) => (typeof window !== 'undefined' && window.assignToolTag ? window.assignToolTag(...args) : undefined);
export const removeToolTag = (...args) => (typeof window !== 'undefined' && window.removeToolTag ? window.removeToolTag(...args) : undefined);
export const renderAssignedTags = (...args) => (typeof window !== 'undefined' && window.renderAssignedTags ? window.renderAssignedTags(...args) : undefined);
export const addProjectPhaseRow = (...args) => (typeof window !== 'undefined' && window.addProjectPhaseRow ? window.addProjectPhaseRow(...args) : undefined);
export const addProjectPhaseTask = (...args) => (typeof window !== 'undefined' && window.addProjectPhaseTask ? window.addProjectPhaseTask(...args) : undefined);
export const addProjectPhaseTaskRow = (...args) => (typeof window !== 'undefined' && window.addProjectPhaseTaskRow ? window.addProjectPhaseTaskRow(...args) : undefined);
export const removeProjectPhaseRow = (...args) => (typeof window !== 'undefined' && window.removeProjectPhaseRow ? window.removeProjectPhaseRow(...args) : undefined);
export const renumberPhasesAndTasks = (...args) => (typeof window !== 'undefined' && window.renumberPhasesAndTasks ? window.renumberPhasesAndTasks(...args) : undefined);
export const recalcProjectBudgetPreview = (...args) => (typeof window !== 'undefined' && window.recalcProjectBudgetPreview ? window.recalcProjectBudgetPreview(...args) : undefined);
export const submitCreateProject = (...args) => (typeof window !== 'undefined' && window.submitCreateProject ? window.submitCreateProject(...args) : undefined);
export const loadProjectsList = (...args) => (typeof window !== 'undefined' && window.loadProjectsList ? window.loadProjectsList(...args) : undefined);
export const changeProjectPageSize = (...args) => (typeof window !== 'undefined' && window.changeProjectPageSize ? window.changeProjectPageSize(...args) : undefined);
export const goToProjectPage = (...args) => (typeof window !== 'undefined' && window.goToProjectPage ? window.goToProjectPage(...args) : undefined);
export const setProjectCxcFilter = (...args) => (typeof window !== 'undefined' && window.setProjectCxcFilter ? window.setProjectCxcFilter(...args) : undefined);
export const filterProjectsList = (...args) => (typeof window !== 'undefined' && window.filterProjectsList ? window.filterProjectsList(...args) : undefined);
export const renderProjectsWithPagination = (...args) => (typeof window !== 'undefined' && window.renderProjectsWithPagination ? window.renderProjectsWithPagination(...args) : undefined);
export const renderProjectsPaginationControls = (...args) => (typeof window !== 'undefined' && window.renderProjectsPaginationControls ? window.renderProjectsPaginationControls(...args) : undefined);
export const renderProjectCardHtml = (...args) => (typeof window !== 'undefined' && window.renderProjectCardHtml ? window.renderProjectCardHtml(...args) : undefined);
export const viewProjectDetails = (...args) => (typeof window !== 'undefined' && window.viewProjectDetails ? window.viewProjectDetails(...args) : undefined);
export const toggleProjectTask = (...args) => (typeof window !== 'undefined' && window.toggleProjectTask ? window.toggleProjectTask(...args) : undefined);
export const updatePhaseStatus = (...args) => (typeof window !== 'undefined' && window.updatePhaseStatus ? window.updatePhaseStatus(...args) : undefined);
export const downloadExcelTemplate = (...args) => (typeof window !== 'undefined' && window.downloadExcelTemplate ? window.downloadExcelTemplate(...args) : undefined);
export const triggerExcelImport = (...args) => (typeof window !== 'undefined' && window.triggerExcelImport ? window.triggerExcelImport(...args) : undefined);
export const handleExcelFileSelected = (...args) => (typeof window !== 'undefined' && window.handleExcelFileSelected ? window.handleExcelFileSelected(...args) : undefined);
export const deleteProject = (...args) => (typeof window !== 'undefined' && window.deleteProject ? window.deleteProject(...args) : undefined);
export const closeAndCulminateProject = (...args) => (typeof window !== 'undefined' && window.closeAndCulminateProject ? window.closeAndCulminateProject(...args) : undefined);
// --- projects_tracking_wbs.js ---
export const resolveCurrentProjectId = (...args) => (typeof window !== 'undefined' && window.resolveCurrentProjectId ? window.resolveCurrentProjectId(...args) : undefined);
export const copyProjectClientTrackingLink = (...args) => (typeof window !== 'undefined' && window.copyProjectClientTrackingLink ? window.copyProjectClientTrackingLink(...args) : undefined);
export const shareProjectViaWhatsApp = (...args) => (typeof window !== 'undefined' && window.shareProjectViaWhatsApp ? window.shareProjectViaWhatsApp(...args) : undefined);
export const printProjectProgressReport = (...args) => (typeof window !== 'undefined' && window.printProjectProgressReport ? window.printProjectProgressReport(...args) : undefined);
export const deleteReceivable = (...args) => (typeof window !== 'undefined' && window.deleteReceivable ? window.deleteReceivable(...args) : undefined);
export const openAddendumModal = (...args) => (typeof window !== 'undefined' && window.openAddendumModal ? window.openAddendumModal(...args) : undefined);
export const submitProjectAddendum = (...args) => (typeof window !== 'undefined' && window.submitProjectAddendum ? window.submitProjectAddendum(...args) : undefined);
export const goToProjectCxC = (...args) => (typeof window !== 'undefined' && window.goToProjectCxC ? window.goToProjectCxC(...args) : undefined);
export const openAddPhaseModal = (...args) => (typeof window !== 'undefined' && window.openAddPhaseModal ? window.openAddPhaseModal(...args) : undefined);
export const submitAddProjectPhase = (...args) => (typeof window !== 'undefined' && window.submitAddProjectPhase ? window.submitAddProjectPhase(...args) : undefined);
export const addProjectTask = (...args) => (typeof window !== 'undefined' && window.addProjectTask ? window.addProjectTask(...args) : undefined);
export const deleteProjectTask = (...args) => (typeof window !== 'undefined' && window.deleteProjectTask ? window.deleteProjectTask(...args) : undefined);
export const openDirectResourceAssignModal = (...args) => (typeof window !== 'undefined' && window.openDirectResourceAssignModal ? window.openDirectResourceAssignModal(...args) : undefined);
export const submitDirectResourceAssign = (...args) => (typeof window !== 'undefined' && window.submitDirectResourceAssign ? window.submitDirectResourceAssign(...args) : undefined);
export const releaseProjectResource = (...args) => (typeof window !== 'undefined' && window.releaseProjectResource ? window.releaseProjectResource(...args) : undefined);
export const onSubstituteReasonChange = (...args) => (typeof window !== 'undefined' && window.onSubstituteReasonChange ? window.onSubstituteReasonChange(...args) : undefined);
export const openSubstituteResourceModal = (...args) => (typeof window !== 'undefined' && window.openSubstituteResourceModal ? window.openSubstituteResourceModal(...args) : undefined);
export const submitSubstituteResource = (...args) => (typeof window !== 'undefined' && window.submitSubstituteResource ? window.submitSubstituteResource(...args) : undefined);
export const openSubstituteMaterialModal = (...args) => (typeof window !== 'undefined' && window.openSubstituteMaterialModal ? window.openSubstituteMaterialModal(...args) : undefined);
export const submitSubstituteMaterial = (...args) => (typeof window !== 'undefined' && window.submitSubstituteMaterial ? window.submitSubstituteMaterial(...args) : undefined);
export const filterSubstituteCatalogList = (...args) => (typeof window !== 'undefined' && window.filterSubstituteCatalogList ? window.filterSubstituteCatalogList(...args) : undefined);
export const switchSubstituteCatalogTab = (...args) => (typeof window !== 'undefined' && window.switchSubstituteCatalogTab ? window.switchSubstituteCatalogTab(...args) : undefined);
export const selectSubstituteItem = (...args) => (typeof window !== 'undefined' && window.selectSubstituteItem ? window.selectSubstituteItem(...args) : undefined);
export const clearSubstituteMaterialSelection = (...args) => (typeof window !== 'undefined' && window.clearSubstituteMaterialSelection ? window.clearSubstituteMaterialSelection(...args) : undefined);
export const toggleAssetActive = (...args) => (typeof window !== 'undefined' && window.toggleAssetActive ? window.toggleAssetActive(...args) : undefined);
export const onQuotationCurrencyChanged = (...args) => (typeof window !== 'undefined' && window.onQuotationCurrencyChanged ? window.onQuotationCurrencyChanged(...args) : undefined);
// --- projects_requisitions.js ---
export const openRequestProjectResourcesModal = (...args) => (typeof window !== 'undefined' && window.openRequestProjectResourcesModal ? window.openRequestProjectResourcesModal(...args) : undefined);
export const setRequestDispatchMode = (...args) => (typeof window !== 'undefined' && window.setRequestDispatchMode ? window.setRequestDispatchMode(...args) : undefined);
export const onRequestDriverChanged = (...args) => (typeof window !== 'undefined' && window.onRequestDriverChanged ? window.onRequestDriverChanged(...args) : undefined);
export const getResourceProjectTag = (...args) => (typeof window !== 'undefined' && window.getResourceProjectTag ? window.getResourceProjectTag(...args) : undefined);
export const populateRequestModalDropdowns = (...args) => (typeof window !== 'undefined' && window.populateRequestModalDropdowns ? window.populateRequestModalDropdowns(...args) : undefined);
export const filterReqDropdown = (...args) => (typeof window !== 'undefined' && window.filterReqDropdown ? window.filterReqDropdown(...args) : undefined);
export const addReqResource = (...args) => (typeof window !== 'undefined' && window.addReqResource ? window.addReqResource(...args) : undefined);
export const onReqMaterialChanged = (...args) => (typeof window !== 'undefined' && window.onReqMaterialChanged ? window.onReqMaterialChanged(...args) : undefined);
export const removeReqResource = (...args) => (typeof window !== 'undefined' && window.removeReqResource ? window.removeReqResource(...args) : undefined);
export const renderReqAssignedTags = (...args) => (typeof window !== 'undefined' && window.renderReqAssignedTags ? window.renderReqAssignedTags(...args) : undefined);
export const navigateToDispatchGuide = (...args) => (typeof window !== 'undefined' && window.navigateToDispatchGuide ? window.navigateToDispatchGuide(...args) : undefined);
export const navigateToProjectGuides = (...args) => (typeof window !== 'undefined' && window.navigateToProjectGuides ? window.navigateToProjectGuides(...args) : undefined);
export const submitRequestProjectResources = (...args) => (typeof window !== 'undefined' && window.submitRequestProjectResources ? window.submitRequestProjectResources(...args) : undefined);
export const openReturnMaterialModal = (...args) => (typeof window !== 'undefined' && window.openReturnMaterialModal ? window.openReturnMaterialModal(...args) : undefined);
export const selectReturnMaterialItem = (...args) => (typeof window !== 'undefined' && window.selectReturnMaterialItem ? window.selectReturnMaterialItem(...args) : undefined);
export const clearReturnMaterialSelection = (...args) => (typeof window !== 'undefined' && window.clearReturnMaterialSelection ? window.clearReturnMaterialSelection(...args) : undefined);
export const onReturnMaterialSelectChanged = (...args) => (typeof window !== 'undefined' && window.onReturnMaterialSelectChanged ? window.onReturnMaterialSelectChanged(...args) : undefined);
export const submitReturnMaterial = (...args) => (typeof window !== 'undefined' && window.submitReturnMaterial ? window.submitReturnMaterial(...args) : undefined);
export const filterReturnMaterialOptions = (...args) => (typeof window !== 'undefined' && window.filterReturnMaterialOptions ? window.filterReturnMaterialOptions(...args) : undefined);
// --- projects_edit.js ---
export const addEditProjectPhaseRow = (...args) => (typeof window !== 'undefined' && window.addEditProjectPhaseRow ? window.addEditProjectPhaseRow(...args) : undefined);
export const onEditProjectMaterialChanged = (...args) => (typeof window !== 'undefined' && window.onEditProjectMaterialChanged ? window.onEditProjectMaterialChanged(...args) : undefined);
export const renderEditAssignedTags = (...args) => (typeof window !== 'undefined' && window.renderEditAssignedTags ? window.renderEditAssignedTags(...args) : undefined);
export const updateEditProjectMaterialsCost = (...args) => (typeof window !== 'undefined' && window.updateEditProjectMaterialsCost ? window.updateEditProjectMaterialsCost(...args) : undefined);
export const addEditProjectResource = (...args) => (typeof window !== 'undefined' && window.addEditProjectResource ? window.addEditProjectResource(...args) : undefined);
export const removeEditProjectResource = (...args) => (typeof window !== 'undefined' && window.removeEditProjectResource ? window.removeEditProjectResource(...args) : undefined);
export const populateEditProjectDropdowns = (...args) => (typeof window !== 'undefined' && window.populateEditProjectDropdowns ? window.populateEditProjectDropdowns(...args) : undefined);
export const openEditProjectModal = (...args) => (typeof window !== 'undefined' && window.openEditProjectModal ? window.openEditProjectModal(...args) : undefined);
export const submitEditProject = (...args) => (typeof window !== 'undefined' && window.submitEditProject ? window.submitEditProject(...args) : undefined);
